### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GSD/GPTL-fortran#1]
I get the following error trying to build tests:

```
make[2]: Entering directory '/home/ed/noaa_tmp/GPTL-fortran/test'
gfortran -DPACKAGE_NAME=\"GPTL-fortran\" -DPACKAGE_TARNAME=\"gptl-fortran\" -DPACKAGE_VERSION=\"5.6.0\" -DPACKAGE_STRING=\"GPTL-fortran\ 5.6.0\" -DPACKAGE_BUGREPORT=\"james.rosinski@noaa.gov\" -DPACKAGE_URL=\"\" -DPACKAGE=\"gptl-fortran\" -DVERSION=\"5.6.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBGPTL=1 -I.  -I../include -I/usr/local/gptl-dev/include  -g -O2 -c -o testinit.o testinit.F90
testinit.F90:2:6:

   use gptl
      1
Fatal Error: Can't open module file ‘gptl.mod’ for reading at (1): No such file or directory
compilation terminated.
```

@jmrosinski is there supposed to be a gptl.mod file somewhere?

**Comment by jmrosinski** [comment]
Ed;

I was able to find and clone the GPTL-fortran repository that you created.
But I have no idea what to type to build it and reproduce the issue you're
seeing. Can you help?

Also, when I try to accept the invitation to collaborate, I get this:

Sorry, we couldn't find that repository invitation. It is possible that the
invitation was revoked or that you are not logged into the invited account.

This error message shows up even though I'm logged in to jmrosinski@github.
Again probably just something I don't understand, but if you can help
that'd be great.

Jim

**Comment by edwardhartnett** [comment]
OK, thanks for reminding me what a .mod file is. It's been a long time since I put together a fortran build system. ;-)

I will see what I can do to move on from the .mod issue...

**Comment by jmrosinski** [comment]
No prob. BTW, the right place to put .mod files at installation time is
$(INSTALLDIR)/include so that -I$(INSTALLDIR)/include can be added by the
(Fortran) user of the installed lib. Also, for testing, any file that has a
Fortran use association (e.g. use gptl) in it needs to have a dependency
for that .mod file (or the associated .o file) added to the Makefile.
