### ISSUE TITLE
File private.h should not be copied as part of "make install"

### ISSUE THREAD

**Issue by jmrosinski** [NOAA-GSD/GPTL-fortran#10]
The file "private.h" is only required as part of the build. It is not needed (by design) by user codes and therefore should not be copied as part of "make install".

**Comment by jmrosinski** [comment]
Oops I'm sorry I submitted this as a Fortran issue but it's actually part of the C library.

**Comment by edhartnett** [comment]
OK, done. I will close this ticket.
