### ISSUE TITLE
Warning from autoreconf -i

### ISSUE THREAD

**Issue by jmrosinski** [NOAA-GSD/GPTL-fortran#11]
On my home machine when I type "autoreconf -i" it complains thusly:

% ~/GPTL-fortran> autoreconf -i
test/Makefile.am:24: warning: variable 'nlreader_SOURCES' is defined but no program or
test/Makefile.am:24: library has 'nlreader' as canonical name (possible typo)

Is this important?

**Comment by edhartnett** [comment]
Fixed. Do a git pull to get changes.
