### ISSUE TITLE
Modify fortran test errtest.F90 to not require human interaction

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GSD/GPTL-fortran#3]
The test errtest.F90 had code that asked for user input, and also relied on the user scanning the output for error messages to determine whether the test succeeded.

In a standard build, we do neither of these things. We have tests that don't require any user-input, which just run tests. We also have to have tests that return 0 for success, non-zero for failure. Test text output is fine, but the test must return either 0 or non-zero, and that's how the build system knows if the test passes.

So I have changed errtest to the following:
```
  write(6,*)'Purpose: test error conditions'

  ! Turn off verbose.
  if (gptlsetoption (GPTLverbose, 0) < 0) stop 2
  
  write(6,*)'testing bad option...'
  if (gptlsetoption (100, 1) .eq. 0) stop 2
  if (gptlinitialize () < 0) stop 3
  if (gptlfinalize () < 0) stop 4
  write(6,*) 'ok!'

  write(6,*)'testing stop never started...'
  if (gptlinitialize () < 0) stop 5
  if (gptlstop ('errtest') .eq. 0) stop 6
  if (gptlfinalize () < 0) stop 7
  write(6,*) 'ok!'

  write(6,*)'testing stop while already stopped...'
  if (gptlinitialize () < 0) stop 8
  if (gptlstart ('errtest') < 0) stop 9
  if (gptlstop ('errtest') < 0) stop 10
  if (gptlstop ('errtest') .eq. 0) stop 11
  write(6,*) 'ok!'

  write(6,*)'testing instance not called...'
  if (gptlstart ('errtest') < 0) stop 12
  if (gptlstop ('errtest') < 0) stop 13
  if (gptlpr (0) < 0) stop 14
  write(6,*) 'ok!'

  stop 0

```
Now, if it gets any unexpected results, it returns non-zero.

**Comment by jmrosinski** [comment]
That's reasonable and probably the correct change. In my old stuff this
code was not run by "make test", that's why it tasked for user input.

**Comment by edhartnett** [comment]
This has already been done, so I will close this ticket.
