### ISSUE TITLE
Missing test file gptlnl need for test nlreader.F90

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GSD/GPTL-fortran#6]
```
ed@mikado:~/noaa_tmp/GPTL-fortran/test$ ./nlreader 
GPTLsetoption: boolean verbose = 1
 nlreader: Testing gptlprocess_namelist...
 gptlprocess_namelist: cannot open namelist file gptlnl
 Failure
```

This used to work for me, so somehow I had a file gptlnl, but now I don't.

Where does this file come from?

**Comment by jmrosinski** [comment]
It's part of my repo, not sure why you don't have it, but it needs to be
part of ftests/. It's attached.

**Comment by edhartnett** [comment]
OK, I added it to the new repo and listed it in the Makefile.am as an EXTRA_DIST. I will close this issue.
