### ISSUE TITLE
PAPI issue with Fortran

### ISSUE THREAD

**Issue by jmrosinski** [NOAA-GSD/GPTL-fortran#9]
configure says this:

checking PAPI library is present, but was not built into C library. Turning PAPI off.... ./configure: line 15494: yes=no: command not found

"Turning PAPI off" sounds right but 'yes=no: command not found' sounds like a problem

Perhaps related, "make check" gives the following even though supposedly PAPI is turned off:

timingModule.F90:12: Error: Can't open included file 'f77papi.h'

Suggestion: Get rid of timingModule.F90 entirely. I should have done this a long time ago--it's superfluous an not needed.

**Comment by edhartnett** [comment]
OK, stand by...

Fixed. And I have removed timingModule.F90 from the build.
